#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH --ntasks=1
#SBATCH --job-name=DOUBLE-GYRE
#SBATCH --account=akwaters
#SBATCH --output=DOUBLE-GYRE.%j
#SBATCH --gres=gpu:1
#SBATCH --no-requeue
#SBATCH -p h100

cd $SLURM_SUBMIT_DIR
#. /usr/share/Modules/init/bash
module purge
module load slurm
module load CUDA
module load NVHPC/25.1-CUDA-12.4.0
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/import/home/kshedstrom/gpu_25/lib
#module list

rm ocean.stats.nvfortran seaice.stats.nvfortran

#conda activate snowy

#
#  Prolog
#
echo " "
echo "++++ Chinook ++++ $PGM_NAME began:    `date`"
echo "++++ Chinook ++++ $PGM_NAME hostname: `hostname`"
echo "++++ Chinook ++++ $PGM_NAME uname -a: `uname -a`"
echo " "
TBEGIN=`echo "print time();" | perl`

#rm diag_table.yaml
#diag-table-to-yaml -f diag_table

srun -n $SLURM_NTASKS /import/c1/AKWATERS/kshedstrom/MOM6_3/build/nvfortran/ocean_only/debug/MOM6

#
#  Epilog
#
TEND=`echo "print time();" | perl`
echo " "
echo "++++ Chinook ++++ $PGM_NAME pwd:      `pwd`"
echo "++++ Chinook ++++ $PGM_NAME ended:    `date`"
echo "++++ Chinook ++++ $PGM_NAME walltime: `expr $TEND - $TBEGIN` seconds"
